// Re-export Prisma enums as TypeScript enums for type safety
// These enums should be used instead of importing directly from @prisma/client
export enum ProgramType {
  FOUNDATIONS = 'FOUNDATIONS',
  ONE_ZERO_ONE = 'ONE_ZERO_ONE',
  LIFTOFF = 'LIFTOFF',
  ALUMNI = 'ALUMNI'
}

export enum JobType {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACT = 'CONTRACT',
  APPRENTICESHIP = 'APPRENTICESHIP',
  INTERNSHIP = 'INTERNSHIP'
}

export enum JobTag {
  FULLY_REMOTE = 'FULLY_REMOTE',
  HYBRID = 'HYBRID',
  IN_PERSON = 'IN_PERSON',
  FRONT_END = 'FRONT_END',
  BACK_END = 'BACK_END',
  FULL_STACK = 'FULL_STACK',
  NON_PROFIT = 'NON_PROFIT',
  START_UP = 'START_UP',
  EDUCATION = 'EDUCATION',
  HEALTHCARE = 'HEALTHCARE',
  FINTECH = 'FINTECH',
  MARKETING = 'MARKETING',
  DATA_SCIENCE = 'DATA_SCIENCE',
  CYBERSECURITY = 'CYBERSECURITY',
  UX_UI_DESIGN = 'UX_UI_DESIGN',
  IT = 'IT',
  PRODUCT_MANAGEMENT = 'PRODUCT_MANAGEMENT',
  GAME_DEVELOPMENT = 'GAME_DEVELOPMENT',
  AI_ML = 'AI_ML',
  CLOUD_COMPUTING = 'CLOUD_COMPUTING',
  DEVOPS = 'DEVOPS',
  BUSINESS_ANALYSIS = 'BUSINESS_ANALYSIS',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA'
}

export enum ApplicationStatus {
  INTERESTED = 'INTERESTED',
  APPLIED = 'APPLIED',
  PHONE_SCREENING = 'PHONE_SCREENING',
  INTERVIEW_STAGE = 'INTERVIEW_STAGE',
  FINAL_INTERVIEW_STAGE = 'FINAL_INTERVIEW_STAGE',
  OFFER_EXTENDED = 'OFFER_EXTENDED',
  NEGOTIATION = 'NEGOTIATION',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  REJECTED = 'REJECTED'
}

export enum AppHistoryStatus {
  APPLIED = 'APPLIED',
  INTERVIEWING = 'INTERVIEWING',
  OFFERED = 'OFFERED',
  HIRED = 'HIRED',
  REJECTED = 'REJECTED'
} 